# Atom properties configuration file up to atomic number 54
# Each atom property is defined by a symbol and a list of values for each atom type
# For the example, see already defined atoms

H:
  name: Hydrogen
  symbol: H
  mass: 1.0 #in atomic mass units
  atomic_number: 1
  valence: 1 #number of valence electrons
  covalent_radius: #in Angstroms
    - 0.32 #single bond

He:
  name: Helium
  symbol: He
  mass: 4.0
  atomic_number: 2
  valence: 0
  covalent_radius:
    - 0.46

Li:
  name: Lithium
  symbol: Li
  mass: 6.9
  atomic_number: 3
  valence: 1
  covalent_radius:
    - 1.33 #single bond
    - 1.24 #double bond
  metallic_radius: 1.52

Be:
  name: Beryllium
  symbol: Be
  mass: 9.0
  atomic_number: 4
  valence: 2
  covalent_radius:
    - 1.02 #single bond
    - 0.90 #double bond
    - 0.85 #triple bond
  metallic_radius: 1.12

B:
  name: Boron
  symbol: B
  mass: 10.8
  atomic_number: 5
  valence: 3
  covalent_radius:
    - 0.85
    - 0.78
    - 0.73

C:
  name: Carbon
  symbol: C
  mass: 12.0
  atomic_number: 6
  valence: 4
  covalent_radius:
    - 0.75
    - 0.67
    - 0.60

N:
  name: Nitrogen
  symbol: N
  mass: 14.0
  atomic_number: 7
  valence: 3
  covalent_radius:
    - 0.71
    - 0.60
    - 0.54

O:
  name: Oxygen
  symbol: O
  mass: 16.0
  atomic_number: 8
  valence: 2
  covalent_radius:
    - 0.63
    - 0.57
    - 0.53

F:
  name: Fluorine
  symbol: F
  mass: 19.0
  atomic_number: 9
  valence: 1
  covalent_radius:
    - 0.64
    - 0.59
    - 0.53

Ne:
  name: Neon
  symbol: Ne
  mass: 20.2
  atomic_number: 10
  valence: 0
  covalent_radius:
    - 0.67
    - 0.96

Na:
  name: Sodium
  symbol: Na
  mass: 23.0
  atomic_number: 11
  valence: 1
  covalent_radius:
    - 1.55
    - 1.6
  metallic_radius: 1.86

Mg:
  name: Magnesium
  symbol: Mg
  mass: 24.3
  atomic_number: 12
  valence: 2
  covalent_radius:
    - 1.39
    - 1.32
    - 1.27
  metallic_radius: 1.60

Al:
  name: Aluminium
  symbol: Al
  mass: 27.0
  atomic_number: 13
  valence: 3
  covalent_radius:
    - 1.26
    - 1.13
    - 1.11
  metallic_radius: 1.43

Si:
  name: Silicon
  symbol: Si
  mass: 28.1
  atomic_number: 14
  valence: 4
  covalent_radius:
    - 1.16
    - 1.07
    - 1.02

P:
  name: Phosphorus
  symbol: P
  mass: 31.0
  atomic_number: 15
  valence: 3
  covalent_radius:
    - 1.11
    - 1.02
    - 0.94

S:
  name: Sulfur
  symbol: S
  mass: 32.1
  atomic_number: 16
  valence: 2
  covalent_radius:
    - 1.03
    - 0.94
    - 0.95

Cl:
  name: Chlorine
  symbol: Cl
  mass: 35.5
  atomic_number: 17
  valence: 1
  covalent_radius:
    - 0.99
    - 0.95
    - 0.93

Ar:
  name: Argon
  symbol: Ar
  mass: 40.0
  atomic_number: 18
  valence: 0
  covalent_radius:
    - 0.96
    - 1.07
    - 0.96

K:
  name: Potassium
  symbol: K
  mass: 39.1
  atomic_number: 19
  valence: 1
  covalent_radius:
    - 1.96
    - 1.93
  metallic_radius: 2.27

Ca:
  name: Calcium
  symbol: Ca
  mass: 40.1
  atomic_number: 20
  valence: 2
  covalent_radius:
    - 1.71
    - 1.47
    - 1.33
  metallic_radius: 1.97

Sc:
  name: Scandium
  symbol: Sc
  mass: 45.0
  atomic_number: 21
  valence: 3
  covalent_radius:
    - 1.48
    - 1.16
    - 1.14
  metallic_radius: 1.62

Ti:
  name: Titanium
  symbol: Ti
  mass: 47.9
  atomic_number: 22
  valence: 4
  covalent_radius:
    - 1.36
    - 1.17
    - 1.08
  metallic_radius: 1.47

V:
  name: Vanadium
  symbol: V
  mass: 50.9
  atomic_number: 23
  valence: 5
  covalent_radius:
    - 1.34
    - 1.12
    - 1.06
  metallic_radius: 1.34

Cr:
  name: Chromium
  symbol: Cr
  mass: 52.0
  atomic_number: 24
  valence: 2
  covalent_radius:
    - 1.22
    - 1.11
    - 1.03
  metallic_radius: 1.28

Mn:
  name: Manganese
  symbol: Mn
  mass: 54.9
  atomic_number: 25
  valence: 7
  covalent_radius:
    - 1.19
    - 1.05
    - 1.03
  metallic_radius: 1.27

Fe:
  name: Iron
  symbol: Fe
  mass: 55.8
  atomic_number: 26
  valence: 2
  covalent_radius:
    - 1.16
    - 1.09
    - 1.02
  metallic_radius: 1.26

Co:
  name: Cobalt
  symbol: Co
  mass: 58.9
  atomic_number: 27
  valence: 2
  covalent_radius:
    - 1.11
    - 1.03
    - 0.96
  metallic_radius: 1.25

Ni:
  name: Nickel
  symbol: Ni
  mass: 58.7
  atomic_number: 28
  valence: 2
  covalent_radius:
    - 1.10
    - 1.01
    - 1.01
  metallic_radius: 1.24

Cu:
  name: Copper
  symbol: Cu
  mass: 63.5
  atomic_number: 29
  valence: 1
  covalent_radius:
    - 1.12
    - 1.15
    - 1.20
  metallic_radius: 1.28

Zn:
  name: Zinc
  symbol: Zn
  mass: 65.4
  atomic_number: 30
  valence: 2
  covalent_radius:
    - 1.18
    - 1.20
  metallic_radius: 1.34

Ga:
  name: Gallium
  symbol: Ga
  mass: 69.7
  atomic_number: 31
  valence: 3
  covalent_radius:
    - 1.24
    - 1.17
    - 1.21
  metallic_radius: 1.35

Ge:
  name: Germanium
  symbol: Ge
  mass: 72.6
  atomic_number: 32
  valence: 4
  covalent_radius:
    - 1.21
    - 1.11
    - 1.14
  metallic_radius: 1.37

As:
  name: Arsenic
  symbol: As
  mass: 74.9
  atomic_number: 33
  valence: 3
  covalent_radius:
    - 1.21
    - 1.14
    - 1.06
  metallic_radius: 1.50

Se:
  name: Selenium
  symbol: Se
  mass: 79.0
  atomic_number: 34
  valence: 2
  covalent_radius:
    - 1.16
    - 1.07
    - 1.07

Br:
  name: Bromine
  symbol: Br
  mass: 79.9
  atomic_number: 35
  valence: 1
  covalent_radius:
    - 1.14
    - 1.09
    - 1.10

Kr:
  name: Krypton
  symbol: Kr
  mass: 83.8
  atomic_number: 36
  valence: 0
  covalent_radius:
    - 1.17
    - 1.21
    - 1.08

Rb:
  name: Rubidium
  symbol: Rb
  mass: 85.5
  atomic_number: 37
  valence: 1
  covalent_radius:
    - 1.10
    - 1.02
  metallic_radius: 2.48

Sr:
  name: Strontium
  symbol: Sr
  mass: 87.6
  atomic_number: 38
  valence: 2
  covalent_radius:
    - 1.85
    - 1.57
    - 1.39
  metallic_radius: 2.15

Y:
  name: Yttrium
  symbol: Y
  mass: 88.9
  atomic_number: 39
  valence: 3
  covalent_radius:
    - 1.63
    - 1.30
    - 1.24
  metallic_radius: 1.80

Zr:
  name: Zirconium
  symbol: Zr
  mass: 91.2
  atomic_number: 40
  valence: 4
  covalent_radius:
    - 1.54
    - 1.27
    - 1.21
  metallic_radius: 1.60

Nb:
  name: Niobium
  symbol: Nb
  mass: 92.9
  atomic_number: 41
  valence: 5
  covalent_radius:
    - 1.47
    - 1.25
    - 1.16
  metallic_radius: 1.46

Mo:
  name: Molybdenum
  symbol: Mo
  mass: 96.0
  atomic_number: 42
  valence: 2
  covalent_radius:
    - 1.38
    - 1.21
    - 1.13
  metallic_radius: 1.39

Tc:
  name: Technetium
  symbol: Tc
  mass: 98.0
  atomic_number: 43
  valence: 7
  covalent_radius:
    - 1.28
    - 1.20
    - 1.10
  metallic_radius: 1.36

Ru:
  name: Ruthenium
  symbol: Ru
  mass: 101.1
  atomic_number: 44
  valence: 2
  covalent_radius:
    - 1.25
    - 1.14
    - 1.03
  metallic_radius: 1.34

Rh:
  name: Rhodium
  symbol: Rh
  mass: 102.9
  atomic_number: 45
  valence: 2
  covalent_radius:
    - 1.25
    - 1.10
    - 1.06
  metallic_radius: 1.34

Pd:
  name: Palladium
  symbol: Pd
  mass: 106.4
  atomic_number: 46
  valence: 2
  covalent_radius:
    - 1.20
    - 1.17
    - 1.12
  metallic_radius: 1.37

Ag:
  name: Silver
  symbol: Ag
  mass: 107.9
  atomic_number: 47
  valence: 1
  covalent_radius:
    - 1.28
    - 1.39
    - 1.37
  metallic_radius: 1.44

Cd:
  name: Cadmium
  symbol: Cd
  mass: 112.4
  atomic_number: 48
  valence: 2
  covalent_radius:
    - 1.36
    - 1.44
  metallic_radius: 1.51

In:
  name: Indium
  symbol: In
  mass: 114.8
  atomic_number: 49
  valence: 3
  covalent_radius:
    - 1.42
    - 1.36
    - 1.46
  metallic_radius: 1.67

Sn:
  name: Tin
  symbol: Sn
  mass: 118.7
  atomic_number: 50
  valence: 4
  covalent_radius:
    - 1.40
    - 1.30
    - 1.32
  metallic_radius: 1.62

Sb:
  name: Antimony
  symbol: Sb
  mass: 121.8
  atomic_number: 51
  valence: 3
  covalent_radius:
    - 1.40
    - 1.33
    - 1.27

Te:
  name: Tellurium
  symbol: Te
  mass: 127.6
  atomic_number: 52
  valence: 2
  covalent_radius:
    - 1.36
    - 1.28
    - 1.21

I:
  name: Iodine
  symbol: I
  mass: 126.9
  atomic_number: 53
  valence: 1
  covalent_radius:
    - 1.33
    - 1.29
    - 1.25

Xe:
  name: Xenon
  symbol: Xe
  mass: 131.3
  atomic_number: 54
  valence: 0
  covalent_radius:
    - 1.31
    - 1.35
    - 1.22 
 
